name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 
#ffff
jobs:
  build-test-lint-typecheck-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - uses: actions/setup-node@v2-beta 
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - run: yarn add --dev jest-junit
      - run: yarn test --coverage
      - run: yarn run test --ci --coverage --reporters=default --reporters=jest-junit
      - run: yarn run test --ci --coverage --testResultsProcessor=jest-junit
      - run: ls coverage
      - run: ls 

      #- run: yarn lint
     # - run: yarn typecheck
    #  - uses: cypress-io/github-action@v2
      #  with:
       #   start: yarn start
        #  wait-on: 'http://localhost:3000'
           #the entire command will automatically be prefixed with "npm"
           #and we need the second "npm" to execute "cypress run ..." command line
          #command-prefix: 'percy exec -- npx'
       # env:
        #  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      
      
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build
      
      - name: Archive test results artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: coverage
            
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: coverage/clover.xml
      #- name: Login to DockerHub
       # uses: docker/login-action@v1
        #with:
         #username: ${{ secrets.DOCKERHUB_USERNAME }}
         #password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: myimage:latest         
    

  
